//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Lesson
    {
        public int LessonID { get; set; }
        public string LessonName { get; set; }
        public string LessonSumary { get; set; }
        public string LessonContent { get; set; }
        public string LessonImage { get; set; }
        public string LessonAuthor { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
